controllers/data_controller.py
from ..helper import read_from_postgres, bar_chart, pie_chart, set_sex
from flask import render_template
import pandas as pd
import numpy as np


def data_controller(category):
    """Controller for data descriptors dashboards for every category

    Args:
        category: category of the data descriptors dashboard selected in the index form
    """
    if category == 'emotions':
        query = 'SELECT "Impressions", "Happy", "Sad", "Anger", "Surprise", "Neutral" FROM winkle_data.scenary_i'
        title_emotions = 'Quantity of weighted emotions detected'
        columns = ['Impressions','Happy', 'Sad', 'Anger', 'Surprise', 'Neutral' ]
        information = {}

        # Calculating weighted sum
        df = read_from_postgres(query=query, columns_names=columns)
        df['Happy (wg)'] = df.apply(lambda x: x.Impressions * x.Happy, axis=1)
        df['Sad (wg)'] = df.apply(lambda x: x.Impressions * x.Sad, axis=1)
        df['Anger (wg)'] = df.apply(lambda x: x.Impressions * x.Anger, axis=1)
        df['Surprise (wg)'] = df.apply(lambda x: x.Impressions * x.Surprise, axis=1)
        df['Neutral (wg)'] = df.apply(lambda x: x.Impressions * x.Neutral, axis=1)

        df = df.drop(columns=columns, axis=1)

        # Naming columns and sorting
        df_emotions = pd.DataFrame(df.sum(), columns=['Weighted sum'])
        df_emotions.index.name = 'Emotions'
        df_emotions =  df_emotions.sort_values('Weighted sum', ascending=False).reset_index()

        # Description
        max_values = df_emotions.values[:3]
        sum_values = df_emotions['Weighted sum'].sum()
        max_percent = [[round(i/sum_values * 100, 2)] for i in max_values[:,1].tolist()]
        values = np.insert(max_values, [2], max_percent, axis=1).tolist()
        information['category'] = category
        information['max_emotions'] = values

        graph_emotions = bar_chart(df_emotions, x_column='Emotions', y_column='Weighted sum', color_column='Emotions', title=title_emotions)
        return render_template('dashboards/data_emotions.html', information=information, graphJSON=graph_emotions)

# --------------------------------------------------------------------------------------------------------------------        
    elif category == 'age':
        information = {}
        query = 'SELECT "Impressions", "Under_18", "Age18", "Age25", "Age35", "Age45", "Age55", "Age65" FROM winkle_data.scenary_i'
        title_age = 'Percentage of weighted ages detected'
        columns = ['Impressions','Under_18', 'Age18', 'Age25', 'Age35', 'Age45', 'Age55', 'Age65']

        df = read_from_postgres(query=query, columns_names=columns)
        df['Under18_wg'] = df.apply(lambda x: x.Impressions * x.Under_18, axis=1)
        df['Age18_wg'] = df.apply(lambda x: x.Impressions * x.Age18, axis=1)
        df['Age25_wg'] = df.apply(lambda x: x.Impressions * x.Age25, axis=1)
        df['Age35_wg'] = df.apply(lambda x: x.Impressions * x.Age35, axis=1)
        df['Age45_wg'] = df.apply(lambda x: x.Impressions * x.Age45, axis=1)
        df['Age55_wg'] = df.apply(lambda x: x.Impressions * x.Age55, axis=1)
        df['Age65_wg'] = df.apply(lambda x: x.Impressions * x.Age65, axis=1)

        df = df.drop(columns=columns)

        df_age = pd.DataFrame(df.sum(), columns=['Sum_wg'])
        df_age.index.name = 'Age'

        graph_age = bar_chart(df_age.reset_index(), x_column='Age', y_column='Sum_wg', color_column='Age', title=title_age)

        information['category'] = category
        information['total'] = len(df)

        return render_template('dashboards/data_descriptors_age.html', category=category, graphJSON=graph_age, information=information)

# --------------------------------------------------------------------------------------------------------------------
    elif category == 'sex':
        information = {}
        query = 'SELECT "ImpMale", "ImpFemale" FROM winkle_data.scenary_i'
        title_sex = 'Percentage of people detected as male or female'
        columns = ['ImpMale', 'ImpFemale']

        df = read_from_postgres(query=query, columns_names=columns)
        df['Sex'] = df.apply(lambda x : set_sex(x.ImpFemale, x.ImpMale),axis=1)
        df_sex = df.groupby('Sex').count().reset_index()[['Sex', 'ImpMale']].rename(columns={'ImpMale': 'count'})

        graph_sex = pie_chart(df_sex, values='count', names='Sex', title=title_sex)
        information['category'] = category
        information['total'] = len(df)
        return render_template('dashboards/data_descriptors_sex.html', category=category, graphJSON=graph_sex, information=information)
    else:
        file_name = f'img/{category}.png'

        return render_template('dashboards.html', title='Data Descriptors', category=category, file_name=file_name)

routes/login_route.py
from flask import Blueprint
from flask_login import login_required
from ..controllers import login_controller, logout_controller


router = Blueprint('auth', __name__)

@router.route('/login', methods=['GET', 'POST'])
def login():
    return login_controller()

@router.route('/logout')
@login_required
def logout():
    return logout_controller()

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block navbar %}
<!-- <div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Emotions</a>
        </div> -->
<!-- <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div> -->
<!-- </div>
</div> -->
<!-- Load an icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
    <a class="navbar-brand" href="/"><i class="fa fa-fw fa-home"></i>Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <!-- <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Analytics Dashboards
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/dashboards/analytics/customer">Customer</a>
                    <a class="dropdown-item" href="/dashboards/analytics/visitors">Visitor</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/dashboards/analytics/asset">Asset</a>
                    <a class="dropdown-item" href="/dashboards/analytics/advertising">Advertising</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Data Descriptors Dashboards
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/dashboards/data/age">Age</a>
                    <a class="dropdown-item" href="/dashboards/data/sex">Sex</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/dashboards/data/emotions">Emotions</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Machine Learning Dashboards
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/dashboards/ml/classifier">Classifier</a>
                    <a class="dropdown-item" href="/dashboards/ml/regressor">Regresor</a>
                </div>
            </li>

        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
    </div>
    <form class="form-inline">
        {% if current_user.is_authenticated %}
        <div><h5 style="color:white"><center>{{current_user.email}}</center></h5></div>
        <button><a href="{{ url_for('auth.logout') }}">Log out</a></button>
        {% else %}
        <button><a href="{{ url_for('auth.login') }}">Login</a></button>
         <!-- TODO: AGREGAR ESTA PARTE EN PAGINA DE PRESENTACIÓN
            <input type="text" class="form-control" placeholder="Username" aria-label="Username"
            aria-describedby="basic-addon1">
        <input type="text" class="form-control" placeholder="Password" aria-label="Password">
        <button type="submit">Login</button>
        -->
        {% endif %}
    </form>
</nav>

{% endblock %}

{% block content %}

<head>
    <title>Emotions APP</title>
    <!-- <div id="preloader">
        <img src=" {{ url_for('static', filename = 'img/preloader.gif') }}" alt="Preloader">
    </div> -->
    <!-- Bootstrap CSS -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
</body>

<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fa-brands fa-facebook-f"></i>
            </a>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="https://hadox.mx/" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>Company name
                    </h6>
                    <p>
                        Here you can use rows and columns to organize your footer content. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Angular</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">React</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Vue</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Laravel</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Pricing</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Orders</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        info@example.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                    <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2022 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">CBPI AI</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
{% endblock %}

templates/data.html
{% extends "base.html" %}

{% block title %}Dashboards{% endblock %}
{% block head %}
    {{ super() }}
    <style>
    </style>
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} Dashboard - {{ category|upper }}</h1>
</div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<div class="chart" id="bargraph">
    <script>
        var graphs = {{ plot|safe }};
        Plotly.plot('bargraph',graphs,{});
    </script>
</div>

<img src="{{ url_for('static', filename=file_name) }}"
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Emotions App - Home Page{% endblock %}
{% block head %}
{{ super() }}
<style>

</style>
{% endblock %}

{% block page_content %}

<div class="video-container">
  <!-- <video id="video" preload muted autoplay loop>
    <source
      src="https://media.istockphoto.com/id/1324915760/es/v%C3%ADdeo/fondo-abstracto-de-una-mujer-hermosa-hecha-de-curvas-e-ia.mp4?s=mp4-640x640-is&k=20&c=P0_8uC1Czr1ynrwbEuFEIPv0uW7ibFOR2HRNlLswcXM="
      type="video/mp4">
  </video> -->
  <div class="jumbotron jumbotron-fluid">
    <h1 class="display-1">Emotions App</h1>
    <p class="lead"> Everyone deserves to lead a happier, more fulfilling life. That's why we're building Emotions
      biometrics to provide personalized recommendations and coaching advice that take your unique emotional state
      into account.</p>
    <hr class="my-4">
    <p>Find out how you can understand your costumer emmotions in just 10 minutes!</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </p>
  </div>
</div>

<div class="container p-3 mb-2 bg-white text-dark">
  <div class="row">
    <h4 class="display-4">Please select the category of the dashboard you want to visualize</h3>
      <div class="col-sm">
        {{ wtf.quick_form(form1) }}
      </div>
      <div class="col-sm">
        {{ wtf.quick_form(form2) }}
      </div>
      <div class="col-sm">
        {{ wtf.quick_form(form3) }}
      </div>
  </div>


  {% endblock %}